### ISSUE TITLE
Make Repository Public

### ISSUE THREAD

**Issue by thorsten-papenbrock** [torbenm/incremental-fds#51]
Dear Developers,

I am writing this as an issue, because I don't have your current email addresses: Can we make this repository public?

Since our paper was successfully published, I got two requests for the code of DynFD. Up until now, I just shared the code via zip and email. It would though be much better to have it publicly available.

Many thanks!
Thorsten

**Comment by torbenm** [comment]
Hi Thorsten,

I made this repo public now.

Kind regards,
Torben
